baseurl = "https://v-kamerdinerov.github.io/"
title = "Vlad Kamerdinerov"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
  author = "Vlad Kamerdinerov"
  info = "Senior Site Reliability Engineer"
  description = "Vlad Kamerdinerov's personal website"
  keywords = "blog,devops,personal"
  avatarurl = "images/avatar.png"

  favicon_32 = "favicon-32x32.png"
  favicon_16 = "favicon-16x16.png"

  since = 2019
  rtl = false
  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []
# Custom remote JS files
customRemoteJS = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/v-kamerdinerov"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-2x fa-linkedin"
  weight = 2
  url = "https://www.linkedin.com/in/vladislav-kamerdinerov/"
[[params.social]]
  name = "Telegram"
  icon = "fa fa-2x fa-telegram"
  weight = 2
  url = "https://t.me/VladFleur"

# Menu links
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"